services:
  mongo:
    image: mongo:latest
    container_name: comments_mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports: 
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_ADMIN_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_ADMIN_PASS}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@${ME_CONFIG_MONGODB_SERVER}:27017/
      - ME_CONFIG_BASICAUTH=false
